/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicewebclient;

import static invoicewebclient.InvoiceGUI.*;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author jana
 */
public class Recipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Recipt() {
        initComponents();
        print();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");

        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        result.setEditable(false);
        result.setColumns(20);
        result.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(668, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            // TODO add your handling code here:
            SaveScreenShot(result,"Receipt.png");
            System.out.println("Saved!!");
        } catch (Exception ex) {
            Logger.getLogger(Recipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JTextArea result;
    // End of variables declaration//GEN-END:variables

    
    public static BufferedImage getScreenShot(Component component){
        BufferedImage image = new BufferedImage(component.getWidth(), component.getHeight(), BufferedImage.TYPE_INT_RGB);
        component.paint(image.getGraphics());
        return image;
    }
    public static void SaveScreenShot(Component component, String filename) throws Exception{
            BufferedImage img = getScreenShot(component);
            ImageIO.write(img, "png", new File (filename));
    }
    public void print() {

        result.setText("--------------------------------------------------------------------------------- \n");
        result.setText(result.getText() +"\t      "+ CompanyName.Companyname +"\n");
        result.setText(result.getText() +"\t"+ CompanyName.address +"\n");
        result.setText(result.getText() +"\t               "+ CompanyName.contactno +"\n");
        result.setText(result.getText()+ "--------------------------------------------------------------------------------- \n");
        result.setText(result.getText()+ "Item Details\t\t\t\tPrice\n");
        result.setText(result.getText() + "--------------------------------------------------------------------------------- \n");
        
        for (int i = 0; i < itemNamelist.size(); i++){
           result.setText(result.getText() + " " +itemNamelist.get(i) + "\t\t\t\t"+ getsubTotallist.get(i)+"\n");
           result.setText(result.getText() + " " +quanttitylist.get(i)+ " x " + unitcostlist.get(i)+"\n");
           result.setText(result.getText() + " SGST : " +getsgstlist.get(i)+ " ( " + sgstpercentlist.get(i)+"% )\n");
           result.setText(result.getText() + " CGST : " +getcgstlist.get(i)+ " ( " + cgstpercentlist.get(i)+"% )\n");
           result.setText(result.getText() + " Cess : " +getcesslist.get(i)+ " ( " + cesspercent1ist.get(i)+"% )\n");
           result.setText(result.getText()+ "\n");
        }
        result.setText(result.getText() +"---------------------------------------------------------------------------------\n");
        result.setText(result.getText() +"\t\tSubtotal\t\t");
        double sub = 0;
        for(int i =0; i < itemNamelist.size();i++){
            sub += getsubTotallist.get(i);
        }
        result.setText(result.getText()+ sub +"\n\n");
        result.setText(result.getText() +"---------------------------------------------------------------------------------\n");
        for (int i = 0; i < itemNamelist.size(); i++){
           result.setText(result.getText() + "\t   SGST : " +" ( " + sgstpercentlist.get(i)+"% )\t\t"+ getsgstlist.get(i)+"\n");
           result.setText(result.getText() + "\t   CGST : " +" ( " + cgstpercentlist.get(i)+"% )\t\t"+ getcgstlist.get(i)+"\n");
           result.setText(result.getText() + "\t   Cess : " +" ( " + cesspercent1ist.get(i)+"% )\t\t"+ getcesslist.get(i)+"\n");
           result.setText(result.getText()+ "\n");
        }
        result.setText(result.getText() +"---------------------------------------------------------------------------------\n");
        
        result.setText(result.getText() + "\n TotalAmount" + "\t\t\t\t"+String.format("₹ %.2f",gettotalCost)+"\n");
        result.setText(result.getText() +"******************************************************\n");
        result.setText(result.getText() +"\n\t"+ "THANK YOU COME AGAIN" +"\n\n");
        result.setText(result.getText() +"******************************************************\n");
        
        
}

}
